import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="h-screen w-screen flex flex-col justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-2xl text-center">Which Stand is more OP?</div>
      <div className="p-8 flex justify-around items-center">
        <div className="flex flex-col items-center">
          <div className="stand-name mb-8 text-xl">Star Platinum</div>
          <img className="h-64 mb-4" src="https://static.jojowiki.com/images/thumb/c/ca/latest/20200927002609/Star_Platinum_SC_Infobox_Anime.png/200px-Star_Platinum_SC_Infobox_Anime.png" alt="" />
          <button className="border rounded-full bg-slate-50  hover:bg-slate-200 text-black py-1 px-8">
            OP</button>       </div>
        <div className="italic">or</div>
        <div className="flex flex-col items-center">
          <div className="stand-name mb-8 text-xl">The World</div>
          <img className="h-64 mb-4" src="https://static.jojowiki.com/images/thumb/7/7e/latest/20191015213103/The_World_Infobox_Anime.png/200px-The_World_Infobox_Anime.png" alt="" />
          <button className="border rounded-full bg-slate-50  hover:bg-slate-200 text-black py-1 px-8">
            OP
          </button>
        </div>
      </div>
    </div>
  )
}
